project:
  name: reddit_game_reviews
  timezone: America/New_York
  db_path: Data_Extraction/Database/Raw_Reviews.db
  src_version: v1

reddit_api:
  client_id: "7u6YFjXKp5GplCa6qb_qMQ"
  client_secret: "5_wKBoOWosQqbsKhJ2VoIUyyjf1qdw"
  user_agent: "reddit_scraper_agent:v1.0 (by u/JSNX_2467) on behalf of CS Capstone Project"
  max_requests_per_min: 20  
  retry:
    max_attempts: 8          
    backoff_base_seconds: 3 
    jitter_seconds: 0.5


collection:
  time_window:
    start_utc: "2023-10-30T00:00:00Z"
    end_utc:   "2025-10-30T23:59:59Z"
  comment_depth: 1
  pull_modes: ["new", "top_day", "top_week", "search"]
  per_subreddit_limits:
    new: 300
    top_day: 150
    top_week: 150
    search: 200

subreddits:
  broad:
    - gaming
    - patientgamers
    - truegaming
    - games
    - pcgaming
    - ShouldIbuythisgame
    - PS5
    - XboxSeriesX
    - NintendoSwitch
    - pcmasterrace
  game_specific:
    Valorant: [VALORANT]
    "League of Legends": [leagueoflegends]
    "Dota 2": [DotA2]
    "Genshin Impact": [Genshin_Impact]
    "PUBG: Battlegrounds": [PUBG]
    "Counter-Strike 2": [GlobalOffensive]
    "Overwatch 2": [Overwatch]
    "Helldivers 2": [Helldivers]
    # Additional game-specific subreddits for the full game list
    "Assassin's Creed Unity": [assassinscreed]
    "Sekiro: Shadows Die Twice": [Sekiro]
    "Escape From Tarkov": [EscapefromTarkov]
    "Crash Bandicoot 4: It's About Time": [CrashBandicoot]
    "Dark Souls (Remastered)": [darksouls]
    "Cuphead": [cuphead]
    "Super Meat Boy": [SuperMeatBoy]
    "Devil May Cry 5": [DevilMayCry]
    "Battlefield 4": [Battlefield_4]
    "Halo: The Master Chief Collection": [halo]
    "Fallout 76": [fo76]
    "Mass Effect: Andromeda": [masseffect]
    "Battlefield 2042": [battlefield2042]
    "Batman: Arkham Knight": [BatmanArkham]
    "No Man's Sky": [NoMansSkyTheGame]
    "Star Wars Battlefront II": [StarWarsBattlefront]
    "SimCity (2013)": [SimCity]
    "Mighty No. 9": [MightyNo9]
    "Fortnite": [Fortnite]
    "Rainbow 6: Siege": [Rainbow6]
    "The Binding of Isaac: Repentance": [bindingofisaac]
    "Getting Over It with Bennett Foddy": [GettingOverIt]
    "Furi": [furi]
    "Jump King": [JumpKing]
    "Mortal Shell": [MortalShell]
    "Street Fighter V": [StreetFighter]
    "APEX Legends": [apexlegends]
    "Call of Duty: Warzone": [CODWarzone]
    "Hogwarts Legacy": [HarryPotterGame]
    "PalWorld": [Palworld]
    "The Lord of the Rings: Gollum": [lotr]
    "Call of Duty: Modern Warfare III": [ModernWarfareIII]
    "Warcraft III: Reforged": [warcraft3]
    "War Thunder": [Warthunder]
    "Delta Force (2024)": []
    "EA SPORTS FC™ 25": [EASportsFC]
  overrides: []

games:
  "Baldur's Gate 3": ["baldur's gate 3", "bg3"]
  "Counter-Strike 2": ["counter-strike 2", "cs2"]
  "Valorant": ["valorant"]
  "Cyberpunk 2077": ["cyberpunk 2077", "cp2077"]
  "Genshin Impact": ["genshin impact", "genshin"]
  "PUBG: Battlegrounds": ["pubg", "playerunknown's battlegrounds"]
  "Overwatch 2": ["overwatch 2", "ow2"]
  "Helldivers 2": ["helldivers 2", "helldivers2"]
  # Additional games and their common aliases
  "Assassin's Creed Unity": ["assassin's creed unity", "ac unity"]
  "Sekiro: Shadows Die Twice": ["sekiro shadows die twice", "sekiro"]
  "League of Legends": ["league of legends"]
  "Escape From Tarkov": ["escape from tarkov", "eft"]
  "Crash Bandicoot 4: It's About Time": ["crash bandicoot 4 it's about time", "crash bandicoot 4", "crash 4"]
  "Dark Souls (Remastered)": ["dark souls remastered"]
  "Cuphead": ["cuphead"]
  "Super Meat Boy": ["super meat boy"]
  "Devil May Cry 5": ["devil may cry 5", "dmc5", "dmc 5"]
  "Battlefield 4": ["battlefield 4", "bf4"]
  "Halo: The Master Chief Collection": ["halo the master chief collection", "halo mcc", "mcc"]
  "Fallout 76": ["fallout 76", "fo76"]
  "Mass Effect: Andromeda": ["mass effect andromeda", "andromeda"]
  "Battlefield 2042": ["battlefield 2042", "bf2042"]
  "Batman: Arkham Knight": ["batman arkham knight", "arkham knight"]
  "No Man's Sky": ["no man's sky", "no mans sky"]
  "Star Wars Battlefront II": ["star wars battlefront ii", "star wars battlefront 2", "battlefront ii", "battlefront 2"]
  "SimCity (2013)": ["simcity 2013", "simcity"]
  "Mighty No. 9": ["mighty no 9", "mighty no. 9", "mighty number 9"]
  "Fortnite": ["fortnite"]
  "DOTA 2": ["dota 2"]
  "Rainbow 6: Siege": ["rainbow 6 siege", "rainbow six siege", "rainbow six: siege"]
  "The Binding of Isaac: Repentance": ["binding of isaac repentance"]
  "Getting Over It with Bennett Foddy": ["getting over it with bennett foddy", "getting over it"]
  "Furi": ["furi"]
  "Jump King": ["jump king"]
  "Mortal Shell": ["mortal shell"]
  "Street Fighter V": ["street fighter v", "street fighter 5", "sfv"]
  "APEX Legends": ["apex legends", "apex"]
  "Call of Duty: Warzone": ["call of duty warzone", "cod warzone"]
  "Hogwarts Legacy": ["hogwarts legacy"]
  "PalWorld": ["palworld"]
  "The Lord of the Rings: Gollum": ["lord of the rings gollum", "lotr gollum"]
  "Call of Duty: Modern Warfare III": ["call of duty modern warfare iii", "modern warfare iii", "modern warfare 3", "cod mw3", "mw3"]
  "Warcraft III: Reforged": ["warcraft iii reforged", "warcraft 3 reforged", "warcraft 3", "warcraft iii"]
  "War Thunder": ["war thunder"]
  "Delta Force (2024)": ["delta force 2024", "delta force"]
  "EA SPORTS FC™ 25": ["ea sports fc 25", "ea sports fc25", "ea sports fc", "fc 25"]

heuristics:
  min_words_for_body_review: 7
  english_ascii_ratio_min: 0.85
  # Use single quotes and escape backslashes so YAML does not interpret
  # the regex patterns.  Without escaping, sequences like \s can be
  # interpreted as unknown escapes during YAML parsing.
  review_title_or_flair_regex: '(review|impressions|first impressions|my thoughts|finished|beat|postmortem|should i buy|worth it|mini review|returning to|after\s+\d+\s*hours)'
  platform_regex: '\\b(pc|steam|ps5|ps4|playstation|xbox(?: series [sx])?|series [sx]|switch|nintendo)\\b'
  playtime_regex: '\\b(\\d{1,3}(?:\\.\\d+)?)\\s*(hours|hrs|h)\\b'

matching:
  order: ["exact", "alias", "fuzzy"]
  fuzzy_max_distance: 2
  require_platform_near_fuzzy: true
  disambiguation: "prefer_longest_exact"

storage:
  table_name_template: "{game_slug}_reddit_game_reviews"
  slug_replace:
    - [" ", "_"]
    - ["'", ""]
    - [":", ""]
    - [",", ""]
    - ["™", ""]

runtime:
  log_level: INFO
  dry_run: false
  save_raw_json: false
  checkpoint_dir: ".checkpoints/reddit"
